add question backend
Kartikey2011yadav/EduWizTesting-Backend pull request #9
Opened 2024-09-30 11:03 UTC by TanishqMehrunkarIIPSDAVV

2024-10-01 10:06 UTC, nishant0708 requested changes

2024-10-01 10:06 UTC, nishant0708 commented on Models/Question.js
Answer bhi save kara teacher se as sting like option hai apple bannana  shoe pear 
aur question hai find odd one out toh answer kya hoga 
"shoe" yeh bhi store kar aur hashed karke store kara

2024-10-01 14:26 UTC, Kartikey2011yadav commented
hashing of answer while storing is still pending @TanishqMehrunkarIIPSDAVV

2024-10-02 08:19 UTC, Kartikey2011yadav commented
@TanishqMehrunkarIIPSDAVV yaha pe bhi pr update kar sakta tha new pr rase karne ki zarurat nhi thi

2024-10-02 08:19 UTC, closed without merging